[package]
name = "breakout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
beryllium = "0.12.3"
glfw = "0.51.0"
bytemuck = "1.13.1"
glam = "0.23.0"
image = "0.24.6"